[project]
site_name = "yads User Guide"
site_description = "Canonical data specification for data platforms."
site_author = "Erich Silva"
#site_url = "https://www.example.com/"
copyright = """
Copyright &copy; 2025 Erich Silva
"""

nav = [
    "index.md",
    {"Introduction" = [
        "intro/quick_start.md",
        "intro/specification.md",
    ]},
    {"API Reference" = [
        "api/spec.md",
        "api/types.md",
        "api/constraints.md",
        {"Loaders" = [
            "api/loaders/index.md",
            "api/loaders/pyarrow.md",
            "api/loaders/polars.md",
            "api/loaders/pyspark.md",
            "api/loaders/yaml.md",
        ]},
        {"Converters" = [
            "api/converters/index.md",
            "api/converters/pyarrow.md",
            "api/converters/polars.md",
            "api/converters/pyspark.md",
            "api/converters/pydantic.md",
            {"SQL" = [
                "api/converters/sql/sqlglot.md",
                "api/converters/sql/sql.md",
            ]}
        ]},
        {"Registries" = [
            "api/registries/index.md",
            "api/registries/filesystem.md",
        ]}
    ]},
    {"Development" = [
        {"Examples" = [
            "develop/examples/index.md",
        ]},
        "develop/extending.md",
        "develop/contributing.md",
    ]}  
]
extra_css = ["stylesheets/extra.css"]

[project.theme]
logo = "assets/texel_logo_squared_azure_no_bg_1000x1000.png"
favicon = "assets/texel_logo_squared_azure_no_bg_1000x1000.png"
language = "en"

features = [
    "header.autohide",
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.indexes",
    # "navigation.expand",
    # "navigation.tabs",
    # "navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
]

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "blue"
accent = "amber"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
primary = "light blue"
accent = "yellow"


[project.theme.icon]
repo = "lucide/smile"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/erich-hs/yads"

[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.toc]
permalink = true


[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
inherited_members = true
show_source = true
show_root_heading = true
show_root_full_path = false
show_symbol_type_heading = true
show_symbol_type_toc = true
